import { useState, useEffect } from 'react';
import { AppBar, Toolbar, Typography, Container, Box, Stack, Paper, Button, Avatar, Menu, MenuItem } from '@mui/material';
import { LogOut, User } from 'lucide-react';
import { QuizGenerator } from './components/QuizGenerator';
import { QuizTaker } from './components/QuizTaker';
import { QuizResults } from './components/QuizResults';
import { AdminPage } from './components/AdminPage';
import { AuthWrapper } from './components/AuthWrapper';
import { LanguageProvider } from './contexts/LanguageContext';
import { useAuth } from './contexts/AuthContext';
import type { Quiz, QuizResult, SoftwareEngineeringTopic } from './types/quiz';
import logo from "./Quiz_logo.jpg"
 

const primary = '#2563eb';
const secondary = '#f5f6fa';

function AppContent() {
  const [currentView, setCurrentView] = useState<'generator' | 'quiz' | 'results' | 'admin'>('generator');
  const [currentQuiz, setCurrentQuiz] = useState<Quiz | null>(null);
  const [quizResult, setQuizResult] = useState<QuizResult | null>(null);
  const { user, logout } = useAuth();
  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);

  // Check if user is admin and redirect accordingly, or auto-start quiz for regular users
  useEffect(() => {
    if (user?.isAdmin) {
      // Automatically redirect admin users to admin dashboard
      setCurrentView('admin');
      window.history.pushState(null, '', '/admin');
    } else if (user && !user.isAdmin && (
      user.quizPreferences || 
      (user.topic && user.difficulty && user.question_type)
    ) && currentView === 'generator') {
      // Auto-start quiz for regular users with preferences
      // Quiz will be auto-generated by QuizGenerator component
    } else if (user && currentView === 'admin') {
      // Redirect non-admin users away from admin page
      setCurrentView('generator');
      window.history.pushState(null, '', '/');
    }
  }, [user, currentView]);

  // Handle browser navigation (simple routing simulation)
  useEffect(() => {
    const handlePopState = () => {
      const currentPath = window.location.pathname;
      if (currentPath.includes('/admin')) {
        if (user?.isAdmin) {
          setCurrentView('admin');
        } else {
          // Redirect non-admin users away from admin page
          window.history.pushState(null, '', '/');
          setCurrentView('generator');
        }
      } else {
        setCurrentView('generator');
      }
    };

    window.addEventListener('popstate', handlePopState);
    return () => window.removeEventListener('popstate', handlePopState);
  }, [user]);

  const handleQuizGenerated = (quiz: Quiz) => {
    setCurrentQuiz(quiz);
    setCurrentView('quiz');
  };
 
  const handleQuizComplete = (result: QuizResult) => {
    setQuizResult(result);
    setCurrentView('results');
  };

  const handleBackToGenerator = () => {
    window.history.pushState(null, '', '/');
    setCurrentView('generator');
    setCurrentQuiz(null);
    setQuizResult(null);
  };

  const handleMenuOpen = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const handleMenuClose = () => {
    setAnchorEl(null);
  };

  const handleLogout = async () => {
    await logout();
    handleMenuClose();
  };

  // Map user preferences to quiz settings
  const getUserQuizSettings = () => {
    if (!user) return {};
    
    // Try to get preferences from nested format first, then direct format
    const preferences = user.quizPreferences || {
      topic: user.topic,
      difficulty: user.difficulty,
      question_type: user.question_type
    };
    
    if (!preferences.topic || !preferences.difficulty || !preferences.question_type) {
      return {};
    }
    
    const { topic, difficulty, question_type } = preferences;
    
    // Map topic to software engineering topics - handle both old and new formats
    const topicMapping: { [key: string]: SoftwareEngineeringTopic } = {
      // New format (SOFTWARE_TOPICS keys)
      'HTML': 'HTML',
      'Python': 'Python',
      '.NET': '.NET',
      'C#': 'C#',
      'SQL': 'SQL',
      'JavaScript': 'JavaScript',
      'TypeScript': 'TypeScript',
      'Java': 'Java',
      'Go': 'Go',
      'Rust': 'Rust',
      'React': 'React',
      'Angular': 'Angular',
      'Vue.js': 'Vue.js',
      'ASP.NET Core': 'ASP.NET Core',
      'Django': 'Django',
      'Spring Boot': 'Spring Boot',
      'SQL Server': 'SQL Server',
      'PostgreSQL': 'PostgreSQL',
      'MySQL': 'MySQL',
      'MongoDB': 'MongoDB',
      'Oracle': 'Oracle',
      'SQLite': 'SQLite',
      // Old format fallbacks
      'Math': 'JavaScript',
      'Science': 'JavaScript',
      'History': 'JavaScript',
      'Geography': 'JavaScript',
    };
    
    // Map question type - handle both old and new formats
    const questionTypeMapping: { [key: string]: 'multiple-choice' | 'code-input' | 'true-false' | 'mixed' } = {
      // New format
      'mixed': 'mixed',
      'multiple-choice': 'multiple-choice',
      'code-input': 'code-input',
      'true-false': 'true-false',
      // Old format
      'MCQ': 'multiple-choice',
      'True/False': 'true-false',
      'Code Input': 'code-input',
    };
    
    return {
      topics: [topicMapping[topic] || 'JavaScript'] as SoftwareEngineeringTopic[],
      difficulty: difficulty.toLowerCase() as 'easy' | 'medium' | 'hard',
      questionType: questionTypeMapping[question_type] || 'mixed',
      numQuestions: 5,
    };
  };

  const renderContent = () => {
    switch (currentView) {
      case 'generator':
        const hasPreferences = user && !user.isAdmin && (
          user.quizPreferences || 
          (user.topic && user.difficulty && user.question_type)
        );
        return (
          <QuizGenerator 
            onQuizGenerated={handleQuizGenerated} 
            autoStart={!!hasPreferences}
            initialSettings={hasPreferences ? getUserQuizSettings() : {}}
          />
        );
      case 'quiz':
        return currentQuiz ? (
          <QuizTaker
            quiz={currentQuiz}
            onQuizComplete={handleQuizComplete}
            onBack={handleBackToGenerator}
          />
        ) : null;
      case 'results':
        return currentQuiz && quizResult ? (
          <QuizResults
            quiz={currentQuiz}
            result={quizResult}
            onBack={handleBackToGenerator}
          />
        ) : null;
      case 'admin':
        return user?.isAdmin ? (
          <AdminPage />
        ) : (
          <Box textAlign="center" py={4}>
            <Typography variant="h6" color="error">
              Access Denied
            </Typography>
            <Typography variant="body2" color="text.secondary" mb={2}>
              You don't have permission to access this page.
            </Typography>
            <Button variant="contained" onClick={handleBackToGenerator}>
              Go Back
            </Button>
          </Box>
        );
      default:
        const defaultHasPreferences = user && !user.isAdmin && (
          user.quizPreferences || 
          (user.topic && user.difficulty && user.question_type)
        );
        return (
          <QuizGenerator 
            onQuizGenerated={handleQuizGenerated} 
            autoStart={!!defaultHasPreferences}
            initialSettings={defaultHasPreferences ? getUserQuizSettings() : {}}
          />
        );
    }
  };

  return (
    <Box minHeight="100vh" bgcolor={secondary} display="flex" flexDirection="column">
      {/* Header */}
      <AppBar position="static" color="inherit" elevation={1} sx={{ mb: 4 }}>
        <Toolbar sx={{ justifyContent: 'space-between' }}>
          <Stack direction="row" alignItems="center" spacing={2}>
            {/* <Box sx={{ p: 1, bgcolor: '#e0e7ff', borderRadius: 2, display: 'flex', alignItems: 'center' }}>
              <Code2 size={28} color={primary} />
            </Box> */}
            <Box>
             <img
            src={logo}
            alt="Logo"
            style={{ width: '250px', height: '80px', margin: '0 auto', display: 'block' }}
          />
            </Box>
            
            {/* Navigation buttons - only show Quiz button for admin users
            {user?.isAdmin && currentView === 'admin' && (
              <Stack direction="row" spacing={1} sx={{ ml: 4 }}>
                <Button
                  variant="outlined"
                  onClick={handleBackToGenerator}
                  size="small"
                >
                  Back to Quiz
                </Button>
              </Stack>
            )} */}
          </Stack>

          {/* User Menu */}
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            <Button
              onClick={handleMenuOpen}
              sx={{
                display: 'flex',
                alignItems: 'center',
                gap: 1,
                color: 'text.primary',
                textTransform: 'none',
                '&:hover': {
                  bgcolor: 'rgba(0,0,0,0.04)',
                },
              }}
            >
              <Avatar sx={{ width: 32, height: 32, bgcolor: primary }}>
                <User size={16} />
              </Avatar>

              <Typography variant="body2" fontWeight={500}>
                {user?.name}
              </Typography>
            </Button>
            <Menu
              anchorEl={anchorEl}
              open={Boolean(anchorEl)}
              onClose={handleMenuClose}
              PaperProps={{
                sx: {
                  mt: 1,
                  minWidth: 200,
                },
              }}
            >
              <MenuItem onClick={handleLogout} sx={{ gap: 1 }}>
                <LogOut size={16} />
                Logout
              </MenuItem>
            </Menu>
          </Box>
        </Toolbar>
      </AppBar>

      {/* Main Content */}
      <Container maxWidth="md" sx={{ flex: 1, py: 4 }}>
        {renderContent()}
      </Container>

      {/* Footer */}
      <Paper elevation={0} sx={{ bgcolor: 'white', borderTop: 1, borderColor: '#e0e0e0', py: 2, mt: 4 }} square>
        <Container maxWidth="md">
          <Typography align="center" variant="body2" color="text.secondary">
        Built by WebAshlar 
        {/* •{' '}
            <Link href="https://github.com" target="_blank" rel="noopener" color="primary">
              View Source
            </Link> */} 
          </Typography>
        </Container>
      </Paper>
    </Box>
  );
}

function App() {
  return (
    <LanguageProvider>
      <AuthWrapper>
        <AppContent />
      </AuthWrapper>
    </LanguageProvider>
  );
}

export default App;
